### ISSUE TITLE
Deploy to firebase

### ISSUE THREAD

**Issue by hajonsoft** [alialiayman/React-Game#6]
As a developer, I want to deploy the game automatically to firebase on merge. Use Github actions to achieve deployment automatically. Update the footer of the first page with the commit Id.

The commit id/commit hash should display at the footer of the first deployed page.

example GitHub action
```
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HAJONSOFTCOM }}'
          channelId: live
          projectId: hajonsoftcom
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```
